Natamate branch
aleklisi/Inteligentny-Pistolet pull request #2
Opened 2018-05-14 20:03 UTC by natamate

Server and console app for policemans

2018-05-14 20:17 UTC, aleklisi requested changes

2018-05-14 20:17 UTC, aleklisi commented on SmartGun/MessagesLibrary/ShotMessage.cs
>          public ShotMessage(int x, int y, string username) : base(x, y, username)
Testuje opcje komentarza ;p

2018-05-14 20:17 UTC, aleklisi commented on SmartGun/MessagesLibrary/ShotMessage.cs
>          public ShotMessage(int x, int y, string username) : base(x, y, username)
public ShotMessage(int x, int y, string username)
public ShotMessage(double x, double y, string username)

2018-05-14 20:26 UTC, aleklisi approved these changes

2018-05-17 19:24 UTC, merged

2018-05-17 19:25 UTC, natamate commented
No conflict merge implemented method which use database